export const GITHUB_REPO = process.env.NEXT_PUBLIC_GITHUB_REPO
export const GITHUB_REPO_ID = process.env.NEXT_PUBLIC_GITHUB_REPO_ID
export const GITHUB_DISCUSSION_CATEGORY =
  process.env.NEXT_PUBLIC_GITHUB_DISCUSSION_CATEGORY
export const GITHUB_DISCUSSION_CATEGORY_ID =
  process.env.NEXT_PUBLIC_GITHUB_DISCUSSION_CATEGORY_ID

export const SENDINBLUE_ENDPOINT = process.env.NEXT_PUBLIC_SENDINBLUE_ENDPOINT
export const SENDINBLUE_API_KEY = process.env.NEXT_PUBLIC_SENDINBLUE_API_KEY
